---
version: "3"
services:
  db:
   image: nagesh2devops/library:dbimage
   ports:
     - "3306:3306"
   deploy:
    replicas: 2

  auth_service:
    image: nagesh2devops/library:auth_image
    ports:
      - "5001:5001"
    deploy:
      replicas: 1

  book:
    image: nagesh2devops/library:book_image
    ports: 
      - "5002:5002"
    deploy:
      replicas: 1
    

  borrow:
     image: nagesh2devops/library:borrow_image
     ports:
      - "5003:5003"
     deploy:
       replicas: 1

  frontend:
    image: nagesh2devops/library:frontend_image
    ports:
      - "5000:5000"
    deploy:
      replicas: 1

      
