---
version: "3"
services:
  db:
   image: nagesh2devops/library01:dbimage
   ports:
     - "3306:3306"
   deploy:
    replicas: 2

  auth_service:
    image: nagesh2devops/library01:auth_image
    ports:
      - "5001:5001"
    deploy:
      replicas: 1

  book_service:
    image: nagesh2devops/library01:book_image
    ports: 
      - "5002:5002"
    deploy:
      replicas: 1
    

  borrow_service:
     image: nagesh2devops/library01:borrow_image
     ports:
      - "5003:5003"
     deploy:
       replicas: 1

  frontend:
    image: nagesh2devops/library01:frontend_image
    ports:
      - "5000:5000"
    deploy:
      replicas: 1

      
